print "Content-type: text/html", "\n\n";
print '<html lang="en">', "\n";
print '<head>', "\n";
print '	<meta charset="UTF-8">', "\n";
print '	<meta name="viewport" content="width=device-width, initial-scale=1.0">', "\n";
print '	<title>Perl example</title>', "\n";
print '	<link rel="stylesheet" href="/css/style.css">', "\n";
print '</head>', "\n";
print '<body>', "\n";
print '	<div class="diva">', "\n";
print '		<h2>PHP example</h2>', "\n";
print '		<div class="aaa">', "\n";
print '			Running on Port :', $ENV{"SERVER_PORT"}, '<BR>', "\n";
print '			Server Software :', $ENV{"SERVER_SOFTWARE"}, '<BR>', "\n";
print '			Server Protocol :', $ENV{"SERVER_PROTOCOL"}, '<BR>', "\n";
print '			CGI Revision :', $ENV{"GATEWAY_INTERFACE"}, '<BR>', "\n";
print '			<a href="/"> go back </a>', "\n";
print '		</div>', "\n";
print '	</div>', "\n";
print '</body>', "\n";
print '</html>', "\n";